### ISSUE TITLE
Controllerクラスについて

### ISSUE THREAD

**Issue by HayatoKikuchi** [uenosuke/GRpeachBoard#18]
ButtonStateが変更されたかを確認できる仕様に変更して頂きたいです．具体的には

①preButtonStateが取得できる関数の追加．
②update()の戻り値をbool型にする．
③変化があったことを示すbool型の関数の追加．

の方法が考えられます．個人的には②の方法が最適だと思います．以下のリンクあるクラスで実装しているのでご確認をお願いします．（田村さんから頂いたクラスを編集したものです．）
[](https://github.com/HayatoKikuchi/Libraries)

**Comment by uenosuke** [comment]
すでにその仕様になっています。
関数のreadButtonの引数を確認してください。

「以下のリンク」が見えません。

**Comment by uenosuke** [comment]
ButtonStateなので，いずれかのボタンに変化があったら，ということですかね？
@ImAdachi ②案の修正お願いできますか？
