### ISSUE TITLE
PathTracking.cppのz軸速度の符号について

### ISSUE THREAD

**Issue by AkihiroKobayashi** [uenosuke/GRpeachBoard#26]
軌道追従を行っていたらz方向の指令が逆に出ているようでした．
194行目のrefVrotと225行目のrefVzgの符号が元は正ですが，負に変えたところ理想通りの挙動になりました．

**Comment by uenosuke** [comment]
結論として，指令角速度に対してロボットの動作が逆方向になっていたことが原因でした．
これはplatformクラスのメカナムホイールの運動学の旋回方向に誤りがあったためであり，この部分の修正を行いました．
またAutoControlの記述でおかしい部分があったため修正しました．

修正版を 3.2.2 としてリリースしました
