### ISSUE TITLE
ジョイスティックと足回りの動く方向が異なる件について

### ISSUE THREAD

**Issue by AkihiroKobayashi** [uenosuke/GRpeachBoard#7]
メカナムの足回りを手動操作でy方向に動かそうとするとジョイスティックが倒れている方向とは逆に動きます．
その他の前後・旋回方向については問題なさそうなのでPlatfrm.cppの119行目から122行目のrefV.yの符号を正負入れ替えるべきかと思います．

**Comment by uenosuke** [comment]
メカナムの場合，167~170行目かと思いますが，確認をお願いします．

**Comment by uenosuke** [comment]
メカナムの運動学を，車輪軸まわりでみて，反時計方向を正方向に取るように変更しました．

**Comment by uenosuke** [comment]
修正し，動作確認を行い，問題ないことを確認しました．
Verを0.1にして公開します．
